# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d34934a7e3940f6cf17b55324c195418a4bb15bfc8857595b9b8aaa057115fa322c98aa52d28b33ab577fce1de0e24acfef42775f406ae1d10ed38ff7bf4a5

test:
  secret_key_base: 22e6f8b2bd0e7956f4feeefa6c00ef67f30f625047c6334d51344e2edb8bc4ef24a81d4b49e23b0aea29b51c5c339e49198b19780707eb671c3fbe6c2f38cd17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
